package com.taint.analysis.utils;

public enum BenchmarkName {
    PIGGYMETRICS_ACCOUNT_SERVICE,
    PIGGYMETRICS_AUTH_SERVICE,
    PIGGYMETRICS_CONFIG,
    PIGGYMETRICS_GATEWAY,
    PIGGYMETRICS_MONITORING,
    PIGGYMETRICS_REGISTRY,
    PIGGYMETRICS_STATISTICS_SERVICE,
    PIGGYMETRICS_NOTIFICATION_SERVICE,
    PIGGYMETRICS_TURBINE_STREAM_SERVICE,
    DEFAULT
}
